<a href="https://colab.research.google.com/github/ruslanleker1663/MLBB-MachineLearningBelajarBareng/blob/main/PEOPLE002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

data load

In [3]:
titanic_dataset_fixed_df = pd.read_csv('/content/sensus_penduduk_kalipare.csv')
df = titanic_dataset_fixed_df
df.head()

,Kode_Kemendagri,Desa_Kelurahan,Kecamatan,Kabupaten,Jumlah_Dusun,Jumlah_RW,Jumlah_RT,Estimasi_Penduduk_Laki_Laki,Estimasi_Penduduk_Perempuan,Total_Penduduk
0,35.07.11.2001,Arjosari,Kalipare,Malang,6,6,37,3600,3550,7150
1,35.07.11.2002,Kalipare,Kalipare,Malang,7,14,75,5200,5150,10350
2,35.07.11.2003,Sumberpetung,Kalipare,Malang,5,14,65,4800,4750,9550
3,35.07.11.2004,Tumpakrejo,Kalipare,Malang,6,6,60,4100,4050,8150
4,35.07.11.2005,Kaliasri,Kalipare,Malang,4,4,31,3100,3050,6150

data slicing

In [5]:
df = df[['Jumlah_Dusun', 'Jumlah_RW', 'Jumlah_RT', 'Estimasi_Penduduk_Laki_Laki', 'Estimasi_Penduduk_Perempuan']]
df.head()

,Jumlah_Dusun,Jumlah_RW,Jumlah_RT,Estimasi_Penduduk_Laki_Laki,Estimasi_Penduduk_Perempuan
0,6,6,37,3600,3550
1,7,14,75,5200,5150
2,5,14,65,4800,4750
3,6,6,60,4100,4050
4,4,4,31,3100,3050

encoding datas

In [6]:
le = LabelEncoder()
df['Jumlah_RW'] = le.fit_transform(df['Jumlah_RW'])
df['Jumlah_RT'] = le.fit_transform(df['Jumlah_RT'])

/tmp/ipykernel_663/849426501.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Jumlah_RW'] = le.fit_transform(df['Jumlah_RW'])
/tmp/ipykernel_663/849426501.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Jumlah_RT'] = le.fit_transform(df['Jumlah_RT'])

result verifying

In [7]:
df.head()

,Jumlah_Dusun,Jumlah_RW,Jumlah_RT,Estimasi_Penduduk_Laki_Laki,Estimasi_Penduduk_Perempuan
0,6,1,3,3600,3550
1,7,3,8,5200,5150
2,5,3,6,4800,4750
3,6,1,5,4100,4050
4,4,0,2,3100,3050

standard

In [8]:
std = StandardScaler()
df['Estimasi_Penduduk_Perempuan'] = std.fit_transform(df[['Estimasi_Penduduk_Perempuan']])

/tmp/ipykernel_663/2912745442.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Estimasi_Penduduk_Perempuan'] = std.fit_transform(df[['Estimasi_Penduduk_Perempuan']])

In [9]:
df.head()

,Jumlah_Dusun,Jumlah_RW,Jumlah_RT,Estimasi_Penduduk_Laki_Laki,Estimasi_Penduduk_Perempuan
0,6,1,3,3600,-0.339158
1,7,3,8,5200,1.072774
2,5,3,6,4800,0.719791
3,6,1,5,4100,0.102071
4,4,0,2,3100,-0.780386

In [10]:
std = StandardScaler()
df['Estimasi_Penduduk_Laki_Laki'] = std.fit_transform(df[['Estimasi_Penduduk_Laki_Laki']])

/tmp/ipykernel_663/2126693013.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Estimasi_Penduduk_Laki_Laki'] = std.fit_transform(df[['Estimasi_Penduduk_Laki_Laki']])

In [11]:
df.head()

,Jumlah_Dusun,Jumlah_RW,Jumlah_RT,Estimasi_Penduduk_Laki_Laki,Estimasi_Penduduk_Perempuan
0,6,1,3,-0.331345,-0.339158
1,7,3,8,1.130471,1.072774
2,5,3,6,0.765017,0.719791
3,6,1,5,0.125472,0.102071
4,4,0,2,-0.788162,-0.780386